catalogs:
  cli:
    '@antfu/eslint-config': ^5.2.1
    '@antfu/ni': ^25.0.0
    '@antfu/nip': latest
    eslint: ^9.34.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
    tsdown: ^0.14.1
    tsx: latest
    typescript: ^5.9.2
  utils:
    tinyexec: ^1.0.1
    cac: ^6.7.14
catalog:
  vue: ^3.5.19
