shellEmulator: true

trustPolicy: no-downgrade

allowBuilds:
  esbuild: true
  simple-git-hooks: true
catalogs:
  cli:
    '@antfu/eslint-config': ^9.1.0
    '@antfu/ni': ^30.2.0
    eslint: ^10.7.0
    nano-staged: ^1.0.2
    simple-git-hooks: ^2.13.1
    tsdown: ^0.22.7
    tsx: latest
    typescript: ~6.0.3
    vitest: ^4.1.10
  utils:
    tinyexec: ^1.2.4
